module.exports = {
  someSidebar: [
    "introduction",
    "download",
    {
      部署: [
        "deployment",
        "integrate",
        "sinomatrix-docker-intellisenseform",
        "deployment-mongodb",
        "deployment-nodejs",
      ],
      应用程序配置: [
        "config-custom",
        "config-disable-modules",
        "config-data-perm",
        "config-resource-publish",
        "config-workflow",
        "config-audit",
        "config-version",
        "config-external-intro",
        "config-remove-test-data",
        "config-user-info",
      ],
      插件开发: [
        "plugin-index",
        {
          入门教程: [
            "guide-setup",
            "guide-hello",
            "guide-button",
            "guide-formfield",
            "guide-watch-form-values",
            "guide-control-button-click",
            "guide-control-button-formitem",
            "guide-global-ui",
            "guide-form-style",
            "guide-i18n",
            "guide-summary",
          ],
          高级教程: [
            "use-app-setting",
            "plugin-field",
            "plugin-button",
            "plugin-detail-page-extend",
            "plugin-css",
            "plugin-module-federation",
            "plugin-test",
          ],
          最佳实践: [
            "plugin-document-structure",
            "plugin-naming-conventions",
            "plugin-dynamic-import",
          ],
        },
        "plugin-faq",
      ],
      样式定制: ["custom-css-pc", "custom-css-mobile", "custom-css-editor"],
      扩展: [
        {
          事件订阅: [
            "sinoform-sdk-event-starter",
            "sinoform-sdk-event-rudiments",
            "sinoform-sdk-event-data",
          ],
        },
        "extend-interface",
      ],
      常见问题: ["deployment-faq", "feature-faq"],
      版本变更记录: [
        "changelog-v1.13.0-alpha.8",
        "changelog-v1.13.0-alpha.1",
        "changelog-v1.13.0-alpha.0",
        "changelog-v1.12.5",
        "changelog-v1.12.4",
        "changelog-v1.12.3",
        "changelog-v1.12.2",
        "changelog-v1.12.1",
        "changelog-v1.12.0",
      ],
      表单配置教程: ["custom-print-template"],
    },
  ],
};
